### ISSUE TITLE
I'm new to OpenSCAD so if anyone can fix this:

### ISSUE THREAD

**Issue by SkyWaterBlaze** [charmaur/PolyDiceGenerator#10]
I used the custom font "VictorianText" and when I render, several numbers are missing, along with the error "ERROR: The given mesh is not closed! Unable to convert to CGAL_Nef_Polyhedron."

Can anyone help?

**Comment by SkyWaterBlaze** [comment]
So the problem is with the number 8 in the font, however I don't know how to fix it's mesh...

**Comment by charmaur** [comment]
Fontforge should do the job. Look around for a tutorial showing how to repair fonts with Fontforge.
