### ISSUE TITLE
Cant render symbol properly

### ISSUE THREAD

**Issue by shawly** [charmaur/PolyDiceGenerator#15]
I've created a custom font with a logo so I can use it for the 20 on the d20.
The problem is that as soon as I render the model the icon won't get rendered properly, which is probably an issue with OpenSCAD itself because of the complexity of the logo.

This is how it renders:
![image](https://user-images.githubusercontent.com/6448794/137978473-b52ca6e8-ab42-4581-9206-13c07435cc82.png)

And this is how it should actually look like:
![image](https://user-images.githubusercontent.com/6448794/137978512-ab7c86b6-30f1-4f4e-b6f1-5a77a2bc3a78.png)

The question is, is there any way I can get this to render properly?

Someone on the Thingiverse forums had this problem with a symbol font as well: https://www.thingiverse.com/groups/openscad/forums/general/topic:9200

Do you think the scaling workaround that was described in the first answer would work here?

I've attached the font here [mindflayer.ttf.zip](https://github.com/charmaur/PolyDiceGenerator/files/7376215/mindflayer.ttf.zip)
The character for the symbol is "\e902" or "".

**Comment by Taiine** [comment]
I will also pipe in and say that as nice as that logo is, the very small lines and the like will be completely lost when 3D printing even if it rendered out properly. Unless you are planning it on a REALLY HUGE jumbo, you're printing something that's not only a triangle, but a very small one with only the edges being around half an inch in size for standard.
