### ISSUE TITLE
Corner Clipping

### ISSUE THREAD

**Issue by CRose91** [charmaur/PolyDiceGenerator#2]
Is there a way to add corner clipping to a specific dice, rather than using the corner clipping function in the rounding section to target all dice? I want to use corner clipping on just the D4.

**Comment by charmaur** [comment]
Sure, deselect all the other dice and render just the d4.

**Comment by CRose91** [comment]
> Sure, deselect all the other dice and render just the d4.

How do you select/ deselect?

**Comment by charmaur** [comment]
Under 'Dice to Draw' change from true to false.

**Comment by CRose91** [comment]
> Under 'Dice to Draw' change from true to false.

Ah okay. Makes sense, thank you for your help, much appreciated.
