### ISSUE TITLE
Please add a D16

### ISSUE THREAD

**Issue by usuallyvexed** [charmaur/PolyDiceGenerator#27]
Any chance that you could add a D16? Thank you.

**Comment by arnoesterhuizen** [comment]
Do you have an example image of a D16?

**Comment by usuallyvexed** [comment]
Sorry, I do not. 


Sent from Yahoo Mail for iPhone


On Sunday, January 14, 2024, 11:37, Arno Esterhuizen ***@***.***> wrote:




Do you have an example image of a D16?
