### ISSUE TITLE
Variable Not Specified

### ISSUE THREAD

**Issue by hayhouse5001** [charmaur/PolyDiceGenerator#28]
Hi, im very new to scad/modeling, I believe i have managed to install BOSL2 properly, however when i load the dice into scad, i get numerous warnings such as: 

[WARNING: variable x not specified as parameter in file PolyDiceGenerator.scad, line 1367](https://github.com/charmaur/PolyDiceGenerator/issues/1367,E:/Scad/PolyDiceGenerator.scad) 
[WARNING: variable y not specified as parameter in file PolyDiceGenerator.scad, line 1367](https://github.com/charmaur/PolyDiceGenerator/issues/1367,E:/Scad/PolyDiceGenerator.scad) 
[WARNING: variable x not specified as parameter in file PolyDiceGenerator.scad, line 1367](https://github.com/charmaur/PolyDiceGenerator/issues/1367,E:/Scad/PolyDiceGenerator.scad)

throughout many lines, and the numbers on the dice are not where they should be, which is probably caused by this error im experiencing. There is probably something simple i am completely missing, i just cant figure out what it is.

**Comment by charmaur** [comment]
Versions of both OpenSCAD and the BOSL2 library are critical. I haven't updated any of this in several years now so you'll have to use the older versions.

Make sure you have the following:
OpenSCAD v2021.01
BOSL2 v2.0.525 (included with PolyDiceGenerator)

**Comment by hayhouse5001** [comment]
Ah, thank you so much! that was the issue. I really appreciate it!
