### ISSUE TITLE
Issues with the D4C and D4P 

### ISSUE THREAD

**Issue by StuartMVG** [charmaur/PolyDiceGenerator#3]
The D4C and D4P are not rendering for me. I turned them on and off and rerendered the models several times, and they do not show up. I tried a previous version, V0.24.3, and the D4C worked in that version. However, when I tried other versions from the changelog, there appear to be several errors. Do you possibly know what could be causing this issue? Thanks :)

**Comment by charmaur** [comment]
If you're getting errors please include them. Specifically, which versions of PolyDiceGenerator, BOSL2, and OpenSCAD are you using?

**Comment by StuartMVG** [comment]
No errors are showing up in the Error-Log. I'm using OpenSCAD 2021.01, PolyDiceGenerator v0.27.1, and the BOSL2 that comes with it, I'm also using a Mac. The problem is that the D4C and D4P models are not showing up, even when I toggle the side buttons on and off and change the code variables. All the other models are working fine, just those two.

**Comment by charmaur** [comment]
Let me know if you continue to have problems after this update.

PolyDiceGenerator v0.27.2
- Fixed d4c/d4p render issues with OpenSCAD 2021.01

**Comment by StuartMVG** [comment]
Amazing! Thank you so much.
