### ISSUE TITLE
dice inside one another

### ISSUE THREAD

**Issue by noel-shade** [charmaur/PolyDiceGenerator#33]
Not sure if it's just something I've done wrong, but every time I open the poly dice generator about 5 of the dice are all in the centre, inside one another. I've tried deleting everything and reinstalling but that was no help. I do have the bosl2 file in the correct place

**Comment by charmaur** [comment]
Sounds like a bosl2 version issue. Are you seeing anything valuable in the Console output?

**Comment by noel-shade** [comment]
I'm seeing the clasic d4, the crystal d4, the d8, the d10s, the d12r and the d20 spread out
The d2, d3 2 of the d4s, d6, d10 and d12 are all in the middle inside one another 
Also the numbers on some of the dice are very off position and when I try to change them nothing happens

**Comment by charmaur** [comment]
Can you show your Console output after hitting preview (f5)?

**Comment by noel-shade** [comment]
<img width="651" alt="Screenshot 2024-01-22 234103" src="https://github.com/charmaur/PolyDiceGenerator/assets/157073855/65991a29-8cd8-4f12-9df3-a419eb4bc3ad">

i'm not too sure if that worked but that should be my screen shot

**Comment by charmaur** [comment]
That worked, but I need to see what's above the warnings, where it shows OpenSCAD and BOSL2 versions.

**Comment by noel-shade** [comment]
ahh sorry 

<img width="956" alt="Screenshot 2024-01-24 004139" src="https://github.com/charmaur/PolyDiceGenerator/assets/157073855/4fa9b13f-97a7-40ae-9ee7-85f451fc13ba">

 is this okay

**Comment by arnoesterhuizen** [comment]
There is a pill request with BOSL2 upgraded that might work for you?
