### ISSUE TITLE
Crashing during render

### ISSUE THREAD

**Issue by ben-christensen** [charmaur/PolyDiceGenerator#4]
Running OpenSCAD v 2021.10 on Windows 10 Pro on a new SSD, 16 GM RAM  , GeForece 1050Ti
Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz   3.50 GHz

I cant seem to get it to render _anything_.

I've disabled all rounding options. Even only tried drawing a single D20, it gets to like 570/1000 and stays there , then crashes with no error that I can see. 

I increased my CGAL cache & PolySet cache to 1000 MB, any help would be greatly appreciated!

**Comment by charmaur** [comment]
There's not much I can do to help without errors. Try uninstalling/reinstalling openscad and running a fresh generator download without alterations.
