### ISSUE TITLE
D4c corning clipping is broken

### ISSUE THREAD

**Issue by soundfx37** [charmaur/PolyDiceGenerator#5]
version: v0.27.2
BOSL 2.0.525
When corner clipping is set to 16 (possibly lower also), the d4c corners do not clip.  Instead a large bounding box is drawn and merged with the d4c.  The corners stick out from the bounding box.  It looks like a subtraction operation isn't being performed properly.
![image](https://user-images.githubusercontent.com/16358824/116012313-aa18b200-a5de-11eb-9fe3-d00c5fb84129.png)

**Comment by charmaur** [comment]
Please let me know if you continue to have problems after this update.

PolyDiceGenerator v0.27.3
- Fixed d4c/d4p corner rounding/clipping bug
- Added per-die spacing adjustment for double digit numbers

Thanks!

**Comment by soundfx37** [comment]
Works like a charm!  Thanks!
