### ISSUE TITLE
Render always fails

### ISSUE THREAD

**Issue by thedragonossuary** [charmaur/PolyDiceGenerator#8]
I've been trying for 2 days to render my dice, and every time it gives me one of two errors and doesn't work. 

The most recent error: 
ERROR: the given mesh is not closed! Unable to convert to CGAL_Nef_Polyhedron. 

The one I was getting before was really long and I didn't copy it down, but it came up multiple times and was something about "all points are the same value, cannot convert" and something about "line 863". 

Please help!

**Comment by charmaur** [comment]
The error indicates a problem with your font. Gaps in or intersecting outlines will cause this. These issues can be repaired in FontForge or the like.

**Comment by thedragonossuary** [comment]
Ok, thank you very much!
