### ISSUE TITLE
Can you add a quick explanation about adding symbols to the docs?

### ISSUE THREAD

**Issue by deathbydragonfire** [charmaur/PolyDiceGenerator#9]
I see where it discusses adding symbols to the dice by using the name, for example mapped to "k".  However I am not super familiar with OpenSCAD and can't figure out where/how I am meant to add symbols to a library and map them to names.  A very quick explanation of this would be great

**Comment by charmaur** [comment]
Are you referring to how lo link a font containing symbols or how to create a font that has symbols? If the latter, I'd rather not support that task under this project.

**Comment by deathbydragonfire** [comment]
Ah, I see.  So you created a font.  And each "letter" is a symbol.  Makes sense.  If you could just explain that, would be clear I think.

**Comment by charmaur** [comment]
I didn't create any fonts, but you get the idea, symbols can be imbedded into fonts in place of letters. If you want to create your own fonts, symbols or not, FontForge is a popular open source font editor.
